### ISSUE TITLE
Some eink display have inverted BUSY pin logic

### ISSUE THREAD

**Issue by hoihu** [mcauser/micropython-waveshare-epaper#2]
see for example:
https://www.waveshare.com/w/upload/e/e6/2.13inch_e-Paper_Datasheet.pdf

so this line:
https://github.com/mcauser/micropython-waveshare-epaper/blob/master/epaper2in13.py#L84
should check for low condition, not high.

 I've tested this on my display and it seems to be correct (not a typo in the datasheet)

**Comment by hoihu** [comment]
@mcauser do you want me to submit a PR for this? I really think it's needed since those displays will not work otherwise...

**Comment by mcauser** [comment]
Hi @hoihu, thanks for looking into this. I've checked each of the datasheets against the Waveshare wiki and code samples. Here are the results.

| Display        | MicroPython | Wiki                                                              | Datasheet | Arduino | RasPi | Panel                                                                         |
|:--------------:|:-----------:| ----------------------------------------------------------------- |:---------:|:-------:|:-----:| ----------------------------------------------------------------------------- |
| 1.54 :warning: | HIGH        | [LOW](https://www.waveshare.com/wiki/1.54inch_e-Paper_Module)     | HIGH      | HIGH    | HIGH  | [GDEH0154D27](http://www.good-display.com/products_detail/productId=365.html) |
| 1.54(B)        | LOW         | [LOW](https://www.waveshare.com/wiki/1.54inch_e-Paper_Module_(B)) | LOW       | LOW     | LOW   | [GDEW0154Z04](http://www.good-display.com/products_detail/productId=307.html) |
| 1.54(C)        | LOW         | [LOW](https://www.waveshare.com/wiki/1.54inch_e-Paper_Module_(C)) | LOW       | LOW     | LOW   | [GDEW0154C39](http://www.good-display.com/products_detail/productId=385.html) |
| 2.13 :warning: | HIGH        | [LOW](https://www.waveshare.com/wiki/2.13inch_e-Paper_HAT)        | LOW       | HIGH    | HIGH  | [GDEH0213B1](http://www.good-display.com/products_detail/productId=346.html)  |
| 2.13(B)        | LOW         | [LOW](https://www.waveshare.com/wiki/2.13inch_e-Paper_HAT_(B))    | LOW       | LOW     | LOW   | [GDEW0213Z16](http://www.good-display.com/products_detail/productId=310.html) |
| 2.13(C)        | LOW         | [LOW](https://www.waveshare.com/wiki/2.13inch_e-Paper_HAT_(C))    | LOW       | LOW     | LOW   | [GDEW0213C38](http://www.good-display.com/products_detail/productId=380.html) |
| 2.7            | LOW         | [LOW](https://www.waveshare.com/wiki/2.7inch_e-Paper_HAT)         | LOW       | LOW     | LOW   | [GDEW027W3](http://www.good-display.com/products_detail/productId=319.html)   |
| 2.7(B)         | LOW         | [LOW](https://www.waveshare.com/wiki/2.7inch_e-Paper_HAT_(B))     | LOW       | LOW     | LOW   | [GDEW027C44](http://www.good-display.com/products_detail/productId=320.html)  |
| 2.9 :warning:  | HIGH        | [HIGH](https://www.waveshare.com/wiki/2.9inch_e-Paper_Module)     | LOW       | HIGH    | HIGH  | [GDEH029A1](http://www.good-display.com/products_detail/productId=251.html)   |
| 2.9(B)         | LOW         | [LOW](https://www.waveshare.com/wiki/2.9inch_e-Paper_Module_(B))  | LOW       | LOW     | LOW   | [GDEW029Z10](http://www.good-display.com/products_detail/productId=308.html)  |
| 2.9(C)         | LOW         | [LOW](https://www.waveshare.com/wiki/2.9inch_e-Paper_Module_(C))  | LOW       | LOW     | LOW   | [GDEW029C32](http://www.good-display.com/products_detail/productId=378.html)  |
| 4.2            | LOW         | [LOW](https://www.waveshare.com/wiki/4.2inch_e-Paper_Module)      | LOW       | LOW     | LOW   | [GDEW042T2](http://www.good-display.com/products_detail/productId=321.html)   |
| 4.2(B)         | LOW         | [LOW](https://www.waveshare.com/wiki/4.2inch_e-Paper_Module_(B))  | LOW       | LOW     | LOW   | [GDEW042Z15](http://www.good-display.com/products_detail/productId=322.html)  |
| 4.2(C)         | LOW         | [LOW](https://www.waveshare.com/wiki/4.2inch_e-Paper_Module_(C))  | LOW       | LOW     | LOW   | [GDEW042C37](http://www.good-display.com/products_detail/productId=379.html)  |
| 5.83           | LOW         | [LOW](https://www.waveshare.com/wiki/5.83inch_e-Paper_HAT)        | LOW       | LOW     | LOW   | [GDEW0583T7](http://www.good-display.com/products_detail/productId=387.html)  |
| 5.83(B)        | LOW         | [LOW](https://www.waveshare.com/wiki/5.83inch_e-Paper_HAT_(B))    | LOW       | LOW     | LOW   | [GDEW0583Z21](http://www.good-display.com/products_detail/productId=383.html) |
| 5.83(C)        | LOW         | [LOW](https://www.waveshare.com/wiki/5.83inch_e-Paper_HAT_(C))    | LOW       | LOW     | LOW   | [GDEW0583C64](http://www.good-display.com/products_detail/productId=388.html) |
| 7.5            | LOW         | [LOW](https://www.waveshare.com/wiki/7.5inch_e-Paper_HAT)         | LOW       | LOW     | LOW   | [GDEW075T8](http://www.good-display.com/products_detail/productId=323.html)   |
| 7.5(B)         | LOW         | [LOW](https://www.waveshare.com/wiki/7.5inch_e-Paper_HAT_(B))     | LOW       | LOW     | LOW   | [GDEW075Z09](http://www.good-display.com/products_detail/productId=324.html)  |
| 7.5(C)         | LOW         | [LOW](https://www.waveshare.com/wiki/7.5inch_e-Paper_HAT_(C))     | LOW       | LOW     | LOW   | [GDEW075C21](http://www.good-display.com/products_detail/productId=381.html)  |

There are 3 drivers which allegedly are using BUSY=HIGH. 1.54", 2.13" and 2.9".

There is not a lot of consistency between the Waveshare wiki, datasheet and Waveshare code examples.

I have a 1.54" and 2.9", so those are the only panels I can test against.

If your 2.13" works with BUSY=LOW, I'm happy to merge that in. Is your display B/W, B/W/Red or B/W/Yellow?

**Comment by hoihu** [comment]
Thats a great overview!

i have a 1.54“ b/w/r and a 4.2“ b/w/y - both are using busy= high to indicate quiet operation. 

Your referenced wiki links point to datasheets that tell the same - so you might check your table vs the datasheets.

**Comment by mcauser** [comment]
Fixed in e892649f003f3f6481243c7e742bd9c2b5850e49
